# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54d6d7ac64ce7649471b423b1ca1ce7e1880315b28385afad3ba89b0f72e3b8e1fcaf722d86970bf77da0b0545a6511ae7baded608d7dd1109ad41a21250d382

test:
  secret_key_base: 4afea7545cb1bf1b7791e4b4cc4e11f7832adfdf1c01471c19c3eb3e4adeb405d21f0a142b6e6314469f383901c55b162c8d6d96db23942c79ce5ab4d4e934ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
